spring.application.name=apptive_3team

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

server.address=0.0.0.0

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# 데이터베이스 설정
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# 이미지 데이터베이스 설정
cloud.aws.s3.bucket=wotd-s3
cloud.aws.region.static=ap-northeast-2
cloud.aws.stack.auto=false
cloud.aws.credentials.access-key=${S3_ACCESS_KEY}
cloud.aws.credentials.secret-key=${S3_SECRET_KEY}

# 카카오 로그인 설정
spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID}
spring.security.oauth2.client.registration.kakao.redirect-uri=${KAKAO_REDIRECT_URI}
spring.security.oauth2.client.registration.kakao.scope=${KAKAO_SCOPE}
spring.security.oauth2.client.registration.kakao.authorization-grant-type=${KAKAO_AUTH_GRANT_TYPE}
spring.security.oauth2.client.registration.kakao.client-name=${KAKAO_CLIENT_NAME}

spring.security.oauth2.client.provider.kakao.authorization-uri=${KAKAO_AUTHORIZATION_URI}
spring.security.oauth2.client.provider.kakao.token-uri=${KAKAO_TOKEN_URI}
spring.security.oauth2.client.provider.kakao.user-info-uri=${KAKAO_USER_INFO_URI}
spring.security.oauth2.client.provider.kakao.user-name-attribute=${KAKAO_USER_NAME_ATTRIBUTE}

# 날씨 조회 설정
weather.api.key=${WEATHER_API_KEY}
weather.api.past-url=${WEATHER_API_PAST_URL}
weather.api.forecast-url=${WEATHER_API_FORECAST_URL}
